version: "3"
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    image: gqlgen-demo
    env_file: 
      - .env
    ports: 
      - 8080:8080
    environment: 
      CONSUMER_KEY: ${CONSUMER_KEY}
      CONSUMER_SECRET: ${CONSUMER_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ACCESS_SECRET: ${ACCESS_SECRET}
